version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    # command: sh -c "python3 main.py --host 0.0.0.0"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
